package net.whiteman.biosanity.world.neoplasm.vein;

import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.server.TickTask;
import net.minecraft.util.RandomSource;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.BaseEntityBlock;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.RenderShape;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.entity.BlockEntityTicker;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.StateDefinition;
import net.minecraft.world.level.block.state.properties.BooleanProperty;
import net.whiteman.biosanity.message.ModMessages;
import net.whiteman.biosanity.message.synchronization.SyncNeoplasmRotPacket;
import net.whiteman.biosanity.world.level.block.ModBlocks;
import net.whiteman.biosanity.world.level.block.entity.ModBlockEntities;
import net.whiteman.biosanity.world.neoplasm.common.INeoplasmNode;
import net.whiteman.biosanity.world.neoplasm.core.NeoplasmCoreBlockEntity;
import net.whiteman.biosanity.world.neoplasm.core.hivemind.HivemindLevel;
import net.whiteman.biosanity.world.neoplasm.rot.NeoplasmRotBlock;
import net.whiteman.biosanity.world.neoplasm.rot.NeoplasmRotBlockEntity;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.*;

import static net.whiteman.biosanity.world.neoplasm.common.NeoplasmConfig.*;
import static net.whiteman.biosanity.world.neoplasm.common.NeoplasmConstants.*;
import static net.whiteman.biosanity.world.neoplasm.resource.ResourceRegistry.*;
import static net.whiteman.biosanity.world.neoplasm.rot.NeoplasmRotBlock.RESOURCE_LEVEL;
import static net.whiteman.biosanity.world.neoplasm.rot.NeoplasmRotBlock.RESOURCE_TYPE;

public class NeoplasmVeinBlock extends BaseEntityBlock implements INeoplasmNode {
    public static final BooleanProperty MATURE = BooleanProperty.create("mature");
    public static final BooleanProperty HAS_NUTRIENT = BooleanProperty.create("has_nutrient");

    public NeoplasmVeinBlock(Properties properties) {
        super(properties);
        this.registerDefaultState(this.stateDefinition.any()
                .setValue(MATURE, false)
                .setValue(HAS_NUTRIENT, false));
    }

    public boolean canSpread(Level level, BlockPos pos, HivemindLevel veinLevel) {
        for (Direction dir : DIRECTIONS) {
            if (isReplaceable(level.getBlockState(pos.relative(dir)), veinLevel)) return true;
        }

        if (findResourceNearby(level, pos) != null) return true;

        return false;
    }

    /** Calculates best grow direction (or absorbs resources if available)
     * TODO list:
     * Maybe make smart resource searching?
     * @param packet An impulse generated by {@link NeoplasmCoreBlockEntity} */
    public void performGrowth(Level level, BlockPos pos, BlockState state, ImpulsePacket packet) {
        if (level.getBlockEntity(pos) instanceof NeoplasmVeinBlockEntity blockEntity) {
            RandomSource random = level.getRandom();
            // Original dir contains original "root vein" direction
            Direction originalDir = blockEntity.growthDirection;
            Direction growDir = null;

            // --- Gravity ---
            // Increases vein chance to grow downwards when there is no wall
            if (hasNoWallNearby(level, pos) && random.nextDouble() < FALL_CHANCE) {
                if (conditions(level, pos, originalDir, Direction.DOWN, packet.hiveLevel())) {
                    growDir = Direction.DOWN;
                }
            }

            // --- Special conditions ---
            if (growDir == null) {
                Direction candidate = (random.nextDouble() < ORIGINAL_DIRECTION_CHANCE)
                        ? originalDir : Direction.getRandom(random);

                if (conditions(level, pos, originalDir, candidate, packet.hiveLevel())) {
                    growDir = candidate;
                } else {
                    // Reroll until we got the best direction for growth (with limited attempts)
                    for (int i = 0; i < REROLL_ATTEMPTS; i++) {
                        Direction rDir = Direction.getRandom(random);
                        if (conditions(level, pos, originalDir, rDir, packet.hiveLevel())) {
                            growDir = rDir;
                            break;
                        }
                    }
                }
            }

            // --- Last chance ---
            // If we don't have better conditions,
            // grow through any replaceable block in random direction
            if (growDir == null) {
                Collection<Direction> shuffled = getShuffledDirections(level.random);
                for (Direction dir : shuffled) {
                    if (isReplaceable(level.getBlockState(pos.relative(dir)), packet.hiveLevel())) {
                        growDir = dir;
                        break;
                    }
                }
            }

            // Deciding what vein supposed to do:
            // Grow or absorb resource
            ResourceResult nearbyResource = findResourceNearby(level, pos);
            // Absorbing resources is more important for us than grow
            if (nearbyResource != null) {
                absorbWithRotBlock(level, pos.relative(nearbyResource.direction), nearbyResource.info, nearbyResource.state, pos, state);
            } else if (growDir != null) {
                BlockState targetState = level.getBlockState(pos.relative(growDir));
                if (isReplaceable(targetState, packet.hiveLevel())) {
                    grow(level, pos, state, growDir, originalDir);
                }
            }
        }
    }

    /** Grows vein in calculated direction by {@code performGrowth}.
     * and sets needed states to blocks */
    private void grow(Level level, BlockPos pos, BlockState state, Direction growDir, Direction originalDir) {
        // Current vein
        BlockState newState = state.setValue(MATURE, true);
        level.setBlock(pos, newState, Block.UPDATE_ALL);

        if (level.getBlockEntity(pos) instanceof NeoplasmVeinBlockEntity be) {
            be.childDirection = growDir;
            be.setChanged();
        }

        // Target vein
        BlockPos targetPos = pos.relative(growDir);

        level.setBlock(targetPos, this.defaultBlockState(), Block.UPDATE_ALL);
        if (level.getBlockEntity(targetPos) instanceof NeoplasmVeinBlockEntity be) {
            be.growthDirection = originalDir;
            be.parentDirection = growDir.getOpposite();
            be.setChanged();
        }
    }

    /** Sets in target position {@link NeoplasmRotBlock},
     * that continue spread infection blocks by himself,
     * and transfers absorbed resources to vein */
    private void absorbWithRotBlock(Level level, BlockPos targetPos, ResourceTypeEntry info, BlockState targetState, BlockPos currentPos, BlockState currentState) {
        // Absorb target
        level.setBlock(targetPos, ModBlocks.NEOPLASM_ROT_BLOCK.get().defaultBlockState()
                .setValue(RESOURCE_TYPE, info.resourceType())
                .setValue(RESOURCE_LEVEL, info.level()), Block.UPDATE_CLIENTS);

        if (level.getBlockEntity(targetPos) instanceof NeoplasmRotBlockEntity blockEntity) {
            blockEntity.setOriginalState(targetState);
            blockEntity.setChanged();

            // Sync a little later for prevent desynchronization
            var server = level.getServer();
            if (server == null) return;
            server.tell(new TickTask(server.getTickCount(), () -> {
                if (level.isLoaded(targetPos) && level.getBlockEntity(targetPos) instanceof NeoplasmRotBlockEntity actualBlockEntity) {
                    if (!actualBlockEntity.isRemoved()) {
                        ModMessages.sendToClientsTracking(new SyncNeoplasmRotPacket(targetPos, actualBlockEntity.saveWithFullMetadata()), actualBlockEntity);
                    }
                }
            }));
        }
    }

    //region Conditions

    private static boolean conditions(Level level, BlockPos pos, Direction originalDir, Direction growDir, HivemindLevel hiveLevel) {
        BlockPos targetPos = pos.relative(growDir);
        BlockState targetState = level.getBlockState(targetPos);

        // Base: can be target replaced?
        if (!isReplaceable(targetState, hiveLevel)) return false;

        // Check neighbor vein limit (except from which we grew)
        if (hasTooManyNeoplasmNearby(level, targetPos, pos, NEIGHBOR_LIMIT)) return false;

        // Don't allow to grow backwards
        if (growDir == originalDir.getOpposite()) return false;

        // Don't allow to climb up without wall
        if (growDir == Direction.UP && hasNoWallNearby(level, pos.relative(growDir))) return false;

        // TEST CONDITION
        if (hasNoWallNearby(level, pos.relative(growDir)) && growDir.getAxis().isHorizontal()) return false;

        return true;
    }

    private static boolean hasNoWallNearby(Level level, BlockPos pos) {
        for (int x = -1; x <= 1; x++) {
            for (int y = -1; y <= 1; y++) {
                for (int z = -1; z <= 1; z++) {
                    if (x == 0 && y == 0 && z == 0) continue;

                    BlockPos adj = pos.offset(x, y, z);
                    BlockState state = level.getBlockState(adj);

                    if (!(state.getBlock() instanceof INeoplasmNode)) {
                        if (state.isCollisionShapeFullBlock(level, adj)) {
                            return false;
                        }
                    }
                }
            }
        }
        return true;
    }

    private static boolean hasTooManyNeoplasmNearby(Level level, BlockPos targetPos, BlockPos currentPos, int limit) {
        int neoplasmCount = 0;
        for (Direction dir : DIRECTIONS) {
            BlockPos neighbor = targetPos.relative(dir);
            BlockState state = level.getBlockState(neighbor);
            if (!neighbor.equals(currentPos) && state.getBlock() instanceof INeoplasmNode node && node.isVein()) {
                neoplasmCount++;
            }
        }
        return neoplasmCount >= limit;
    }

    //endregion

    private record ResourceResult(Direction direction, ResourceTypeEntry info, BlockState state) {}

    private static ResourceResult findResourceNearby(Level level, BlockPos pos) {
        Collection<Direction> shuffled = getShuffledDirections(level.random);
        for (Direction dir : shuffled) {
            BlockPos checkPos = pos.relative(dir);
            BlockState state = level.getBlockState(checkPos);
            ResourceTypeEntry info = getResourceInfo(state.getBlock());

            if (info.resourceType().isResource()) {
                return new ResourceResult(dir, info, state);
            }
        }
        return null;
    }

    @Override public boolean isVein() { return true; }

    @Override
    public void setPlacedBy(Level level, @NotNull BlockPos pos, @NotNull BlockState state, LivingEntity placer, @NotNull ItemStack stack) {
        if (!level.isClientSide) {
            if (level.getBlockEntity(pos) instanceof NeoplasmVeinBlockEntity be) {
                be.growthDirection = HORIZONTAL_DIRECTIONS[level.random.nextInt(HORIZONTAL_DIRECTIONS.length)];
            }
        }
    }

    @Override public BlockEntity newBlockEntity(@NotNull BlockPos pos, @NotNull BlockState state) {
        return new NeoplasmVeinBlockEntity(pos, state);
    }

    @Override public @NotNull RenderShape getRenderShape(@NotNull BlockState state) {
        return RenderShape.MODEL;
    }

    @Override
    public void onRemove(BlockState state, @NotNull Level level, @NotNull BlockPos pos, BlockState newState, boolean isMoving) {
        if (state.getBlock() == newState.getBlock()) {
            return;
        }
        // If the living end of our vein is destroyed, we make the previous block young again
        // (and all neighbors too)
        for (Direction dir : DIRECTIONS) {
            BlockPos neighborPos = pos.relative(dir);
            BlockState neighborState = level.getBlockState(neighborPos);

            if ((state.hasProperty(MATURE) && !state.getValue(MATURE)) || hasNonMatureNearby(level, pos)) {
                if (neighborState.hasProperty(MATURE) && neighborState.getValue(MATURE)) {
                    level.setBlock(neighborPos, neighborState.setValue(MATURE, false), Block.UPDATE_ALL);

                    // Test particle
                    level.levelEvent(2001, neighborPos, Block.getId(neighborState));
                }
            }
        }
        super.onRemove(state, level, pos, newState, isMoving);
    }

    private static boolean hasNonMatureNearby(Level level, BlockPos pos) {
        for (Direction dir : DIRECTIONS) {
            BlockPos checkPos = pos.relative(dir);
            BlockState state = level.getBlockState(checkPos);

            if (state.hasProperty(MATURE) && !state.getValue(MATURE)) {
                return true;
            }
        }
        return false;
    }

    @Override protected void createBlockStateDefinition(StateDefinition.Builder<Block, BlockState> builder) {
        builder.add(MATURE, HAS_NUTRIENT);
    }

    @Override
    public @Nullable <T extends BlockEntity> BlockEntityTicker<T> getTicker(Level pLevel, @NotNull BlockState pState, @NotNull BlockEntityType<T> pBlockEntityType) {
        if (pLevel.isClientSide()) {
            return null;
        }

        return createTickerHelper(pBlockEntityType, ModBlockEntities.NEOPLASM_VEIN_BE.get(),
                (pLevel1, pPos, pState1, pBlockEntity) -> pBlockEntity.tick(pLevel1, pPos, pState1, pBlockEntity));
    }
}